### ISSUE TITLE
Warning <p> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by maplesyrupweb** [maplesyrupweb/react-full-stack-blog#11]
validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
    at p
    at div
    at CommentForm (http://localhost:3000/static/js/bundle.js:401:3)
    at p
    at ArticlePage (http://localhost:3000/static/js/bundle.js:802:88)

**Comment by maplesyrupweb** [comment]
corrected issue in ArticlePage.js and CommentForm.js
